### ISSUE TITLE
Invitation of incoporating LoveDA dataset into MMSegmentation.

### ISSUE THREAD

**Issue by MengzhangLI** [Junjue-Wang/LoveDA#1]
Hi, I am member of OpenMMLab who develops [MMSegmentation](https://github.com/open-mmlab/mmsegmentation). Our vision is provide up-to-date methods and dataset(i.e., benchmark) for researchers and community around the world.

First, congrats for acceptance of NeurIPS'21. I think this dataset and benchmark would definitely help Remote Sensing Image field where semantic segmentation plays an important role. 

Frankly speaking, right now we do not have too much human resources. Would you like to help us incpoorate your dataset into MMSegmentation? We appreciate all contibutors and users, here is our [contributing details](https://github.com/open-mmlab/mmsegmentation/blob/master/.github/CONTRIBUTING.md). 

I think if LoveDA is provided by MMSegmentation, it could let more people use & cite this excellent work, especially for those who want to establish standard segmentation benchmark.

Looking forward to your reply. Wish you all the best.

Best,

**Comment by Junjue-Wang** [comment]
> OK, maybe we could have a meeting next few weeks.
> 
> Feel free to call us if you have any problems.
> 
> Best,

I have already pulled a request on mmsegmentation, please see https://github.com/open-mmlab/mmsegmentation/pull/1006#issue-1040452742.
Due to hardware limitations and not being familiar with this project, I haven't done any unit testing.
I would appreciate it if you can help me check the modifications : )
