### ISSUE TITLE
Hello, can you provide the mIoU of these networks on the val set, thank you

### ISSUE THREAD

**Issue by Demo122** [Junjue-Wang/LoveDA#13]
![image](https://user-images.githubusercontent.com/37685456/143530662-be9057d1-cdb5-41a7-bf55-950bf84090a8.png)

**Comment by Junjue-Wang** [comment]
Please refer to these results implemented with MMSegmentation:
https://github.com/open-mmlab/mmsegmentation/pull/1028#issuecomment-964814514

**Comment by Demo122** [comment]
> 
thanks，i will see

**Comment by Demo122** [comment]
你好，我在codalab上提交的lovada测试集结果得到的分数一直是0，我提交的result.zip是按照要求提交的，内容是这样，





，请问是什么原因呢，谢谢
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Junjue-Wang/LoveDA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月26日(星期五) 中午1:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Junjue-Wang/LoveDA] Hello, can you provide the mIoU of these networks on the val set, thank you (Issue #13)





 
Please refer to these results implemented with MMSegmentation:
 open-mmlab/mmsegmentation#1028 (comment)
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Junjue-Wang** [comment]
我猜您可能是选择文件夹进行压缩，应该全选所有png，然后进行压缩

**Comment by Demo122** [comment]
对的，我是选择文件夹压缩，我现在试试选择png压缩，谢谢您这么快回复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月5日(星期天) 晚上8:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Junjue-Wang/LoveDA] Hello, can you provide the mIoU of these networks on the val set, thank you (Issue #13)





 
我猜您可能是选择文件夹进行压缩，应该全选所有png，然后进行压缩
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Junjue-Wang** [comment]
没事儿，如果有其他问题随时联系我，我如果看到第一时间会回复~

**Comment by Demo122** [comment]
你好，我想问能否提供test的label，我想自己测试model找出效果最好的模型


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Junjue-Wang/LoveDA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月5日(星期天) 晚上8:42
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Junjue-Wang/LoveDA] Hello, can you provide the mIoU of these networks on the val set, thank you (Issue #13)





 
没事儿，如果有其他问题随时联系我，我如果看到第一时间会回复~
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Junjue-Wang** [comment]
目前test标签是不对外开放的，您可以再validation上测试设计最好的模型，然后提交codalab系统获取test精度。

**Comment by Demo122** [comment]
你好，
能否提供您论文图5中的单独高清分割结果供我参考，谢谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Junjue-Wang/LoveDA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月26日(星期五) 中午1:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Junjue-Wang/LoveDA] Hello, can you provide the mIoU of these networks on the val set, thank you (Issue #13)





 
Please refer to these results implemented with MMSegmentation:
 open-mmlab/mmsegmentation#1028 (comment)
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Junjue-Wang** [comment]
Fig5论文原始图片已上传
链接：https://pan.baidu.com/s/1GJEeJ8yw65Qj80c-gWoxbA 
提取码：2333

**Comment by Demo122** [comment]
你好，请问这部分数据是否写错了？

**Comment by Junjue-Wang** [comment]
> 你好，请问这部分数据是否写错了？

有什么问题吗

**Comment by Demo122** [comment]
没有我就问一下，因为我引用了您论文中的部分数据，所以想问问，这个是笔误还是重新实验的结果




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月25日(星期五) 中午11:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Junjue-Wang/LoveDA] Hello, can you provide the mIoU of these networks on the val set, thank you (Issue #13)





  
你好，请问这部分数据是否写错了？
  
有什么问题吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Junjue-Wang** [comment]
> 没有我就问一下，因为我引用了您论文中的部分数据，所以想问问，这个是笔误还是重新实验的结果
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年2月25日(星期五) 中午11:47 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; "State ***@***.***&gt;; 主题: Re: [Junjue-Wang/LoveDA] Hello, can you provide the mIoU of these networks on the val set, thank you (Issue #13) 你好，请问这部分数据是否写错了？ 有什么问题吗 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

没太清楚你说的具体内容是什么？

**Comment by Demo122** [comment]
请看图中unet的miou




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月25日(星期五) 中午11:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Junjue-Wang/LoveDA] Hello, can you provide the mIoU of these networks on the val set, thank you (Issue #13)





  
没有我就问一下，因为我引用了您论文中的部分数据，所以想问问，这个是笔误还是重新实验的结果
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年2月25日(星期五) 中午11:47 收件人: @.&gt;; 抄送: @.&gt;; "State @.&gt;; 主题: Re: [Junjue-Wang/LoveDA] Hello, can you provide the mIoU of these networks on the val set, thank you (Issue #13) 你好，请问这部分数据是否写错了？ 有什么问题吗 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you modified the open/close state.Message ID: @.***&gt;
  
没太清楚你说的具体内容是什么？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Junjue-Wang** [comment]
> 请看图中unet的miou
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年2月25日(星期五) 中午11:54 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; "State ***@***.***&gt;; 主题: Re: [Junjue-Wang/LoveDA] Hello, can you provide the mIoU of these networks on the val set, thank you (Issue #13) 没有我就问一下，因为我引用了您论文中的部分数据，所以想问问，这个是笔误还是重新实验的结果 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年2月25日(星期五) 中午11:47 收件人: @.&gt;; 抄送: @.&gt;; "State @.&gt;; 主题: Re: [Junjue-Wang/LoveDA] Hello, can you provide the mIoU of these networks on the val set, thank you (Issue #13) 你好，请问这部分数据是否写错了？ 有什么问题吗 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you modified the open/close state.Message ID: @.***&gt; 没太清楚你说的具体内容是什么？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

没有写错。这个表格是LoveDA test set上的结果
