### ISSUE TITLE
Submission status stuck in 'running' for a long time

### ISSUE THREAD

**Issue by leahyyy** [Junjue-Wang/LoveDA#14]
I have submitted the results, but it is stuck in 'running' for a long time, say more than 2 days. Is it because of the old Codalab server?

**Comment by Junjue-Wang** [comment]
Yes, the Codalab runs slowly because of the many pipelines on this server. You can resubmit the results or tell me your user id so I can help you re-run.

**Comment by Junjue-Wang** [comment]
These two results are re-runed.
![image](https://user-images.githubusercontent.com/27996790/143854302-f90f0061-b6f5-4f7e-90f3-d8fbbaf3b717.png)

**Comment by leahyyy** [comment]
Thank you for your help. There is one result. It seems to be still very slow, could you please delete my processes that have not run yet?

**Comment by leahyyy** [comment]
Because of re-run, many processes are added without a description, which is useless.
Thanks.

**Comment by Junjue-Wang** [comment]
Once the status changes from "Submitted" to "Running". It reveals that the process is running. You can see in the leaderboard that the running time is less than 4 mintues.

**Comment by leahyyy** [comment]
Are you considering moving the competition to a new codalab server? Other competitions seem to have the same problem because of the old server. [https://github.com/codalab/codalab-competitions/issues/3045](url)

**Comment by Junjue-Wang** [comment]
Thanks for your suggestion. We have moved the contest to https://codalab.lisn.upsaclay.fr/competitions/421.

**Comment by leahyyy** [comment]
Thank you so much! Another question is whether the val set annotation will be fixed and re-released?

**Comment by Junjue-Wang** [comment]
This is a very important but very time-consuming task. I will continue to collect suggestions and revise the whole dataset.
You are also welcome to help upload the revised data, we will mark the contribution in the next version
