### ISSUE TITLE
为什么我这里报错

### ISSUE THREAD

**Issue by superJack2222** [Junjue-Wang/LoveDA#15]
- [ ] 

- [ ]
![python](https://user-images.githubusercontent.com/19429672/143865213-910fa40d-8562-4658-8527-904130ea1113.png)

**Comment by superJack2222** [comment]
why i meet this questions ?

**Comment by Junjue-Wang** [comment]
请检查ever是否安装正确，preprocess.albu.ToTensor() 函数参考:
https://github.com/Z-Zheng/ever/blob/71bb0c08a433705d7d8380b7b92d461598382659/ever/api/preprocess/albu.py#L22

**Comment by superJack2222** [comment]
thank you .i have resolve this problem. thanks for your help
