### ISSUE TITLE
Sorry, failed to upload file.

### ISSUE THREAD

**Issue by csliujw** [Junjue-Wang/LoveDA#16]
你好，我在提交 LoveDA Unsupervised Domain Adaptation 测试结果的时候，出现 Sorry, failed to upload file. 是目前还无法提交吗？

**Comment by Junjue-Wang** [comment]
由于之前的codalab服务老旧，我们最近将其迁移至新的服务器请您移步：https://codalab.lisn.upsaclay.fr/competitions/424#results

**Comment by Junjue-Wang** [comment]
现在是可以提交的，您可以再次尝试提交

**Comment by csliujw** [comment]
目前提交还是提示 Sorry, failed to upload file

**Comment by Junjue-Wang** [comment]
目前新的服务器好像在维护~
![image](https://user-images.githubusercontent.com/27996790/144255269-9c6c2694-1f56-47e7-ba4b-6881a5c83229.png)
https://codalab.lisn.upsaclay.fr/
您可以试试旧的？

**Comment by Junjue-Wang** [comment]
Please refer to the Codalab info:
https://github.com/codalab/codalab-competitions/issues/3053#issuecomment-985417639
