### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by superJack2222** [Junjue-Wang/LoveDA#17]
when i run Semantic_Segmentation/train.py  , this bug occured ,how to resolved i
![lovvea](https://user-images.githubusercontent.com/19429672/144378811-71dd2bf4-f1d0-413c-85d3-b55c0d7100d8.png)
t？

**Comment by Junjue-Wang** [comment]
You should follow this bash command.
bash ./scripts/train_hrnetw32.sh
