### ISSUE TITLE
The different resolutions in training and testing

### ISSUE THREAD

**Issue by Luffy03** [Junjue-Wang/LoveDA#18]
I found that in the training process, the input resolution is 512x512, while in the test phase, the input resolution is 1024x1024. Would you please tell me why?

**Comment by Junjue-Wang** [comment]
This is a common practice in semantic segmentation. We ignore this difference due to the GPU memory limitation.
We also tried a larger size 768x768 but got a negligible increase in accuracy.

**Comment by Luffy03** [comment]
Why don't you perform slide-predictions with 512x512 size in the test process?  Will it impact the final results? I assume that the test resolution should be set to the same.

**Comment by Junjue-Wang** [comment]
Of course. This will improve the final results and you can try.
