### ISSUE TITLE
happen this issue

### ISSUE THREAD

**Issue by superJack2222** [Junjue-Wang/LoveDA#19]
AttributeError: module 'ever.cfg' has no attribute 'config'  how can i resolve it

**Comment by Junjue-Wang** [comment]
Please try to design your script like the provided [bash](https://github.com/Junjue-Wang/LoveDA/blob/f895e816e765d0689b898898498d1494bf03c7d4/Semantic_Segmentation/scripts/predict_test.sh) and check the environment.
