### ISSUE TITLE
Bug  => FileNotFoundError: No such file: '/media/qq/0CBE052B0CBE052B/dataset/LoveDA/Unsupervised_Domian_Adaptation/2868.png'

### ISSUE THREAD

**Issue by csliujw** [Junjue-Wang/LoveDA#26]
CBST_Train.py文件的源代码  
          target_config = cfg.TARGET_DATA_CONFIG
            target_config['mask_dir'] = save_pseudo_label_path # 会报错 FileNotFoundError
            logger.info(target_config)
            targetloader = LoveDALoader(target_config)
            targetloader_iter = Iterator(targetloader)

应该修正为
            target_config = cfg.TARGET_DATA_CONFIG
            target_config['mask_dir'] = [save_pseudo_label_path] # 将路径包裹为一个列表可解决此错误
            logger.info(target_config)
            targetloader = LoveDALoader(target_config)
            targetloader_iter = Iterator(targetloader)

**Comment by Junjue-Wang** [comment]
Thanks for your careful revison. I have fixed this.
