### ISSUE TITLE
你好，请问你这个数据集有lable文件吗？我在百度网盘下载的数据没有对应的label文件

### ISSUE THREAD

**Issue by olongfen** [Junjue-Wang/LoveDA#28]

**Comment by Junjue-Wang** [comment]
有啊 有label文件 请仔细浏览一遍

**Comment by olongfen** [comment]
好的谢谢，请问这个颜色值对应的类别是什么呢？

**Comment by Junjue-Wang** [comment]
麻烦使用前请阅览我的github readme
![image](https://user-images.githubusercontent.com/27996790/147526565-fdc0de05-f86d-4e5a-ab7d-272c69c3b028.png)

**Comment by olongfen** [comment]
不好意思，我表达的意思不明确，是label对应的结果值，现在已在代码里面找到了
