### ISSUE TITLE
Dataset links for Google drive return a 404 error

### ISSUE THREAD

**Issue by AnkushMalaker** [Junjue-Wang/LoveDA#31]
The links mentioned on the README.md of this repository as well as the competition page for google drive of the dataset are broken as of 30-01-2022 and return a 404 error. Please update the link with a working one.

**Comment by Junjue-Wang** [comment]
I have just checked the links you mentioned. And I found it still works.
How about try it again or use the Zenodo: https://doi.org/10.5281/zenodo.5706578

**Comment by Junjue-Wang** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        I have just checked the links you mentioned. And I found it still works.
        
    
        
            
        
    
    
        
        

        
    

    On 1/30/2022 19:40，Ankush ***@***.***> wrote： 



The links mentioned on the README.md of this repository as well as the competition page for google drive of the dataset are broken as of 30-01-2022 and return a 404 error. Please update the link with a working one.

**Comment by AnkushMalaker** [comment]
> I have just checked the links you mentioned. And I found it still works. How about try it again or use the Zenodo: https://doi.org/10.5281/zenodo.5706578

It does seem to be working now. Me and my team of different systems were getting the same error, but seeing as its resolved I'll close this issue. Thanks.
