### ISSUE TITLE
question: why stop at INFO:ever.core.logger:HRNetEncoder: pretrained = True

### ISSUE THREAD

**Issue by Tracy-git** [Junjue-Wang/LoveDA#34]
thanks your work .
When I train with train_hrnetw32.sh, the log output stops at INFO:ever.core.logger:HRNetEncoder: pretrained = True, there is no other log output, no error is reported, and the graphics card is not called .
have you ever meet this issues?
![微信图片_20220219143824](https://user-images.githubusercontent.com/56622046/154789777-42476699-d376-4ce7-ac1f-ea87485ecc57.png)
![微信图片_20220219143909](https://user-images.githubusercontent.com/56622046/154789796-eeb97fb2-ae49-43cc-8dc2-07e2be043c05.png)

**Comment by Junjue-Wang** [comment]
![image](https://user-images.githubusercontent.com/27996790/154791010-c3776a10-fcac-4485-a916-4ecd1437098b.png)
Please check your runtime error. It indicates that 'Address already in use'. I think you should check your runnin script and revised another id
