### ISSUE TITLE
Potential shift in class labels

### ISSUE THREAD

**Issue by wpkel** [Junjue-Wang/LoveDA#38]
Following up on the discussion from #23, I was wondering whether in the context of the segmantic segmentation task there could be a shift in class labels between the data on which the [pretrained model hrnetw32.pth](https://drive.google.com/drive/folders/1xFn1d8a4Hv4il52hLCzjEy_TY31RdRtg) was trained on and the [data](https://drive.google.com/drive/folders/1ibYV0qwn4yuuh068Rnc-w4tPi0U0c-ti) provided in this repo.

Here I have visualised the true and predicted segmentations on training image 1338 for 2 different `COLOR_MAP`-s from the repo ([render.py](https://github.com/Junjue-Wang/LoveDA/blob/2a94964fb28134775c0c45e409f8bad83e872e01/Semantic_Segmentation/render.py#L4-L13) and [data.loveda.py](https://github.com/Junjue-Wang/LoveDA/blob/2a94964fb28134775c0c45e409f8bad83e872e01/Semantic_Segmentation/data/loveda.py#L22-L30))

<img width="500" alt="Screenshot 2022-03-26 at 10 06 23" src="https://user-images.githubusercontent.com/15845236/160234758-357b606a-085f-4b0d-81f3-71a2a2814faa.png">

<img width="500" alt="Screenshot 2022-03-26 at 10 06 31" src="https://user-images.githubusercontent.com/15845236/160234759-d45731c7-122f-493b-86fd-2063d82dd667.png">

Based on the input image we can see that the colours are correct for the top left and bottom right visualisations. 
Also, the black colours in top right image corresponds to label _IGNORE_ with RGB values (0,0,0) while in the bottom left the black colour has RGB values (7,7,7), which seems to be because in data.loveda.py the `COLOR_MAP` only has 7 classes and with indexing 0-6 with _agriculture_ having label 7 in the masked images, it is not colour mapped.

This seems to be related to the difference between labels in the [current repo](https://github.com/Junjue-Wang/LoveDA#dataset-and-contest):

> Category labels: background – 1, building – 2, road – 3, water – 4, barren – 5, forest – 6, agriculture – 7. And the no-data regions were assigned 0 which should be ignored. The provided data loader will help you construct your pipeline.

and the ones described on [CodaLab](https://codalab.lisn.upsaclay.fr/competitions/421#learn_the_details-evaluation):

> Classes indexes: Background - 0, Building - 1, Road - 2, Water - 3, Barren - 4, Forest - 5, Agriculture - 6

Could this class label offset be the case or perhaps there is an alternative explanation which I have not thought about?

**Comment by wpkel** [comment]
Code used for the visualisations: https://gist.github.com/wpkel/faa0839c4af62cc06c418c04f1c8308b

**Comment by Junjue-Wang** [comment]
Yes, I think this problem comes from the class label offset. 
The predicted label ranges from 0 - 6 and the gt labels range from 0 - 7 (includes the ignore index).
So the [render.py](https://github.com/Junjue-Wang/LoveDA/blob/2a94964fb28134775c0c45e409f8bad83e872e01/Semantic_Segmentation/render.py#L4-L13) is used for gt label and the [data.loveda.py](https://github.com/Junjue-Wang/LoveDA/blob/2a94964fb28134775c0c45e409f8bad83e872e01/Semantic_Segmentation/data/loveda.py#L22-L30) is used for predicted label.

**Comment by wpkel** [comment]
Thank you! That clarifies the issue.
