### ISSUE TITLE
Can you provide the pre-training weights of the adversarial learning？

### ISSUE THREAD

**Issue by csliujw** [Junjue-Wang/LoveDA#39]
Hi, I would like to use the visualized results of Adaptseg and CLAN for comparison, could you  provide the pre-training weights (Rural to Urban weights) of these two networks?

**Comment by Junjue-Wang** [comment]
There are the weights you needed 
https://pan.baidu.com/s/1omy-h8kYW8t1ZX0pOsugvw?pwd=2333
