### ISSUE TITLE
What tools do you use to label and verify its accuracy?

### ISSUE THREAD

**Issue by angelaAH** [Junjue-Wang/LoveDA#42]
Do you use some professional geographic software through the spectrum and other information for automatic labeling ?

**Comment by Junjue-Wang** [comment]
No, we label these images by hand

**Comment by angelaAH** [comment]
> No, we label these images by hand

Thanks a lot for the quick reply. Do you use labelme or something like that?

**Comment by Junjue-Wang** [comment]
We use the ArcGIS

**Comment by angelaAH** [comment]
> We use the ArcGIS

Got it!  Thank you very much for the kind reply!
