### ISSUE TITLE
AttributeError: module 'ever' has no attribute 'viz'

### ISSUE THREAD

**Issue by Luffy03** [Junjue-Wang/LoveDA#5]
seems my installed ever module's version is wrong
would you please tell me how to fix this problem? thank you very much

**Comment by Junjue-Wang** [comment]
Sorry for the trouble. We have not integrated this visualization tool ever, but you can find our implementation [here](https://github.com/Z-Zheng/SimpleCV/blob/4fa67581441ad150e82b3aa2c394a921f74e4ecd/simplecv/_impl/viz/segm.py).
Please let me know if this can address your concern.
Feel free to ask me if you have any further questions.

**Comment by Junjue-Wang** [comment]
> seems my installed ever module's version is wrong would you please tell me how to fix this problem? thank you very much

I have already fixed this bug. Please re-forked our repo :)

**Comment by Luffy03** [comment]
> > seems my installed ever module's version is wrong would you please tell me how to fix this problem? thank you very much
> 
> I have already fixed this bug. Please re-forked our repo :)

The problem still exists

**Comment by Junjue-Wang** [comment]
> > > seems my installed ever module's version is wrong would you please tell me how to fix this problem? thank you very much
> > 
> > 
> > I have already fixed this bug. Please re-forked our repo :)
> 
> The problem still exists

Did you re-downloaded our code? I have revised this in the module and eval.py.

**Comment by Luffy03** [comment]
already solved, thanks

**Comment by Junjue-Wang** [comment]
> already solved, thanks

Glad to see the problem resolved. Feel free to ask me if you have any further questions.
