### ISSUE TITLE
Meaning of line 228 in the Unsupervised_Domian_Adaptation/utils/tools.py

### ISSUE THREAD

**Issue by simonep1052** [Junjue-Wang/LoveDA#56]
Hello, 

Thank you very much for making your excellent work open to the public.

May I ask you the meaning of line 228 in [tools.py](https://github.com/Junjue-Wang/LoveDA/blob/master/Unsupervised_Domian_Adaptation/utils/tools.py) for Unsupervised Domain Adaptation? I found that when running `bash ./scripts/predict_cbst.sh`, it will generate a bug saying AttributeError: 'NoneType' object has no attribute 'info'. This bug is due to line 228 and also the default setting `_default_logger=None`. Hence, I wonder what this line is for. Also, I would like to let you know that after commenting the line 228, the command can be run successfully.

Many thanks for your help.

**Comment by Junjue-Wang** [comment]
This is a logger to print the details of your training or testing

**Comment by simonep1052** [comment]
I see. Thank you very much.
