### ISSUE TITLE
About the accuracy of the CodaLab website

### ISSUE THREAD

**Issue by Hcshenziyang** [Junjue-Wang/LoveDA#57]
Why is the domain adaptation MIOU on the CodaLab site so high? Shouldn't the "Oracle" MIOU provided in the paper be the highest MIOU for this domain adaptation task?

**Comment by Junjue-Wang** [comment]
Oracle setting is not necessarily the highest precision. Sometimes UDA methods will see unlabelled target images, which maybe generate better distributions.

**Comment by Hcshenziyang** [comment]
> Oracle 设置不一定是最高精度的。有时 UDA 方法会看到未标记的目标图像，这可能会生成更好的分布。

谢谢你的回复。我的方法在你们的数据集上跑的效果并不好……折腾了好久，太难了。所以你的意思是部分排行榜方法可能并没有完全按照你们论文中提供的数据集划分方式，而是在训练阶段也加入了无标签的目标域Test进行训练？这样的话配合一些自监督方法，可能确实更有效一些……另外我觉得，你们数据集不仅仅是城乡分布差距，在城市或者农村数据集内部，地区不同所带来的差异影响同样巨大，这让训练更加困难，一些多源域训练方法不知道会不会有效。

**Comment by Hcshenziyang** [comment]
> Oracle setting is not necessarily the highest precision. Sometimes UDA methods will see unlabelled target images, which maybe generate better distributions.

还有一个小白问题了，希望大佬能够解答……就是图像载入时候通常都会有标准化处理，有些是减去均值，有些是减去均值除以标准差。我很好奇这一步标准化的操作真的有效吗？我在之前数据集上测试过未处理的0~255图像和减去均值的图像，输入网络后的训练精度大差不差，不知道是不是之前那个数据集自身偏差不大所导致的，不知道大佬有没有测试过这个问题？

**Comment by Junjue-Wang** [comment]
> 

这个数据比较难，利用未标记的测试影像也是属于正常的UDA settings

**Comment by Junjue-Wang** [comment]
> > Oracle setting is not necessarily the highest precision. Sometimes UDA methods will see unlabelled target images, which maybe generate better distributions.
> 
> 还有一个小白问题了，希望大佬能够解答……就是图像载入时候通常都会有标准化处理，有些是减去均值，有些是减去均值除以标准差。我很好奇这一步标准化的操作真的有效吗？我在之前数据集上测试过未处理的0~255图像和减去均值的图像，输入网络后的训练精度大差不差，不知道是不是之前那个数据集自身偏差不大所导致的，不知道大佬有没有测试过这个问题？

有些情况差异大，有些情况差异小

**Comment by Hcshenziyang** [comment]
感谢！
