### ISSUE TITLE
Results submitted to Codalab

### ISSUE THREAD

**Issue by Luffy03** [Junjue-Wang/LoveDA#6]
The results submitted to the CodaLab get zero score and zero ExecutionTime. I wonder is it any wrong with the CodaLab or it is just my own mistake. The output class index is 0~6 with 1024*1024 pixels.

**Comment by Junjue-Wang** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        I have already checked your submit.zip
        The compression format is wrong.Select all pictures to compress instead of compressing the folder.
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                kingdrone
                            
                            
                                
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 11/5/2021 ***@***.***> wrote： 



The results submitted to the CodaLab get zero score and zero ExecutionTime. I wonder is it any wrong with the CodaLab or it is just my own mistake. The output class index is 0~6 with 1024*1024 pixels.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Luffy03** [comment]
> I have already checked your submission ZIP. The compression format is wrong. Please try to select all PNGs to compress instead of compressing the folder.
> […](#)
> The results submitted to the CodaLab get zero score and zero ExecutionTime. I wonder is it any wrong with the CodaLab or it is just my own mistake. The output class index is 0~6 with 1024*1024 pixels.

Solved! Thank you very much

**Comment by Junjue-Wang** [comment]
You are welcome.

**Comment by Junjue-Wang** [comment]
> > I have already checked your submission ZIP. The compression format is wrong. Please try to select all PNGs to compress instead of compressing the folder.
> > […](#)
> > The results submitted to the CodaLab get zero score and zero ExecutionTime. I wonder is it any wrong with the CodaLab or it is just my own mistake. The output class index is 0~6 with 1024*1024 pixels.
> 
> Solved! Thank you very much

You're welcome.

**Comment by Luffy03** [comment]
I wonder how can i watch the detailed results

**Comment by Junjue-Wang** [comment]
> I wonder how can i watch the detailed results

You can download the detailed results like this:
![image](https://user-images.githubusercontent.com/27996790/140461928-aee68e59-c2a0-45ed-9ea8-cf10d552563b.png)

**Comment by Luffy03** [comment]
Done, thank you
