### ISSUE TITLE
数据集标注精度疑问

### ISSUE THREAD

**Issue by csliujw** [Junjue-Wang/LoveDA#7]
你好，我观察了下数据集中的标注数据。有些图片标注的似乎不是很精细；
有些图片，道路中的forest会一起被标注为道路；
有些图片中的建筑物会出现漏标，只标一部分；
有些图片中的建筑物还会把周围比较多的背景包括进去；
有些图片中占比较小的forest会被漏标，有些图片又会标记这些较小的forest。
如 Val/Urban/3518 建筑物只标注了一部分 Val/Urban/3532
请问，Test 数据集中的标注也会出现这样的情况吗？还是 Test 数据集中的标注比 Train 和 Val 的要更精细一些。

**Comment by Junjue-Wang** [comment]
感谢您指出标注存在了一些问题，目前来看，这些细碎的问题不影响大数据驱动下的模型训练。 可以参考MMCV给我们数据集Benchmark的结果。 (https://github.com/open-mmlab/mmsegmentation/pull/1006#issuecomment-962886677)
测试集是我们仔细检查过的，应该错误会少一些。我们也正在整理收集现有标注错误，希望您也可以协助我们，上传给我们修改后的正确标注，我们也会有进一步的更新。
