### ISSUE TITLE
The annotation of validation fold in Rural is very poor.

### ISSUE THREAD

**Issue by Dawn-bin** [Junjue-Wang/LoveDA#71]
The annotation of validation fold in Rural is very poor. A large amount of pixels are labeled into background class.

![image1](https://user-images.githubusercontent.com/40346249/239949462-2e9834f2-bae1-4139-bac2-788b5efdc9b9.png)
![image2](https://user-images.githubusercontent.com/40346249/239950352-c047ba21-0702-4faa-83f7-8dcef0747751.png)

The definition of background class is ambiguous. It should be refined or replaced with other class.

**Comment by Junjue-Wang** [comment]
Version 2 will be released for these revisions.

**Comment by wzp8023391** [comment]
I met the same question after I trained the DlinkNet model on this dataset, I found that this model's performance was abysmal, I hope you should pay more attention to the quality of your dataset

**Comment by Junjue-Wang** [comment]
Maybe you can further develop your DlinkNet, are hyperparams suitable? And we will release Version 2 for this dataset as soon as possible.
