### ISSUE TITLE
Submission fails

### ISSUE THREAD

**Issue by j2jeong** [Junjue-Wang/LoveDA#73]
I submitted the .zip file on the submit tab of the competition site, but all the submissions failed. Here is the error log.

`WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/tmp/codalab/tmp6dUz6Z/run/program/evaluate.py:153: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  gt = imread(truthp).astype(np.float) - 1
Traceback (most recent call last):
  File "/tmp/codalab/tmp6dUz6Z/run/program/evaluate.py", line 158, in 
    metric.forward(gt[valid_inds], mask[valid_inds])
  File "/tmp/codalab/tmp6dUz6Z/run/program/evaluate.py", line 22, in forward
    cm = sparse.coo_matrix((v, (y_true, y_pred)), shape=(self.num_classes, self.num_classes), dtype=np.float32)
  File "/opt/conda/lib/python3.9/site-packages/scipy/sparse/_coo.py", line 196, in __init__
    self._check()
  File "/opt/conda/lib/python3.9/site-packages/scipy/sparse/_coo.py", line 281, in _check
    if self.nnz > 0:
  File "/opt/conda/lib/python3.9/site-packages/scipy/sparse/_base.py", line 299, in nnz
    return self.getnnz()
  File "/opt/conda/lib/python3.9/site-packages/scipy/sparse/_coo.py", line 243, in getnnz
    raise ValueError('row, column, and data array must all be the '
ValueError: row, column, and data array must all be the same length`

 I looked at the number and format of the files, but I think there is no problem.
 Can you check if I submitted it wrong?
 My name in codalab is j2.

**Comment by Junjue-Wang** [comment]
I have checked your submission. The labels need to be consistent with the provided format, [1024, 1024], unit8.

**Comment by Junjue-Wang** [comment]
You have submitted the colorful masks wrongly.

**Comment by j2jeong** [comment]
Thank you for your reply. I was able to submit properly.
