### ISSUE TITLE
语义分割训练过程中的num_classes是8还是7 ？

### ISSUE THREAD

**Issue by Voruarn** [Junjue-Wang/LoveDA#74]
因为我用 cross_entropy loss训练语义分割模型时，num_classes为7会报错，num_classes为8可以正常运行。
但是Dataset and Contest部分却说 And the no-data regions were assigned 0 which should be ignored.  有点困惑。

**Comment by Junjue-Wang** [comment]
num_classes=7,我的dataloader自动把0变成了负1 ignore了

**Comment by Voruarn** [comment]
> num_classes=7,我的dataloader自动把0变成了负1 ignore了

**Comment by Voruarn** [comment]
好的，谢谢
